//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG_example_CallingPNwebservice1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smartorg.com/extAPI/", ConfigurationName="ServiceReference1.ProjectSoap")]
    public interface ProjectSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/TestAuth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string TestAuth(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/UpdateCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BG_example_CallingPNwebservice1.ServiceReference1.ActionResult UpdateCategories(string username, string password, string externalID, string Categories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/TeamProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BG_example_CallingPNwebservice1.ServiceReference1.ActionResult TeamProject(string username, string password, string externalID, string team64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/DestroyAllProjects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] DestroyAllProjects(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/GetProjectsExtIDs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BG_example_CallingPNwebservice1.ServiceReference1.ProjectDefs GetProjectsExtIDs(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/CreateProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BG_example_CallingPNwebservice1.ServiceReference1.ActionResult CreateProject(string username, string password, string projectName, string projectDescription, string correlationID, string division, string templateName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smartorg.com/extAPI/")]
    public partial class ActionResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultCodeField;
        
        private string messageField;
        
        private string correlationIDField;
        
        private string[] warningsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("ResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
                this.RaisePropertyChanged("CorrelationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] Warnings {
            get {
                return this.warningsField;
            }
            set {
                this.warningsField = value;
                this.RaisePropertyChanged("Warnings");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smartorg.com/extAPI/")]
    public partial class ProjectDef : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string correlationIDField;
        
        private string divisionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
                this.RaisePropertyChanged("CorrelationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
                this.RaisePropertyChanged("Division");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smartorg.com/extAPI/")]
    public partial class ProjectDefs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ProjectDef[] defsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public ProjectDef[] Defs {
            get {
                return this.defsField;
            }
            set {
                this.defsField = value;
                this.RaisePropertyChanged("Defs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ProjectSoapChannel : BG_example_CallingPNwebservice1.ServiceReference1.ProjectSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ProjectSoapClient : System.ServiceModel.ClientBase<BG_example_CallingPNwebservice1.ServiceReference1.ProjectSoap>, BG_example_CallingPNwebservice1.ServiceReference1.ProjectSoap {
        
        public ProjectSoapClient() {
        }
        
        public ProjectSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestAuth(string username, string password) {
            return base.Channel.TestAuth(username, password);
        }
        
        public BG_example_CallingPNwebservice1.ServiceReference1.ActionResult UpdateCategories(string username, string password, string externalID, string Categories) {
            return base.Channel.UpdateCategories(username, password, externalID, Categories);
        }
        
        public BG_example_CallingPNwebservice1.ServiceReference1.ActionResult TeamProject(string username, string password, string externalID, string team64) {
            return base.Channel.TeamProject(username, password, externalID, team64);
        }
        
        public string[] DestroyAllProjects(string username, string password) {
            return base.Channel.DestroyAllProjects(username, password);
        }
        
        public BG_example_CallingPNwebservice1.ServiceReference1.ProjectDefs GetProjectsExtIDs(string username, string password) {
            return base.Channel.GetProjectsExtIDs(username, password);
        }
        
        public BG_example_CallingPNwebservice1.ServiceReference1.ActionResult CreateProject(string username, string password, string projectName, string projectDescription, string correlationID, string division, string templateName) {
            return base.Channel.CreateProject(username, password, projectName, projectDescription, correlationID, division, templateName);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smartorg.com/extAPI/", ConfigurationName="ServiceReference1.ProjectHttpGet")]
    public interface ProjectHttpGet {
        
        // CODEGEN: Generating message contract since the operation TestAuth is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/ProjectHttpGet/TestAuthRequest", ReplyAction="http://smartorg.com/extAPI/ProjectHttpGet/TestAuthResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BG_example_CallingPNwebservice1.ServiceReference1.TestAuthResponse TestAuth(BG_example_CallingPNwebservice1.ServiceReference1.TestAuthRequest request);
        
        // CODEGEN: Generating message contract since the operation UpdateCategories is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/ProjectHttpGet/UpdateCategoriesRequest", ReplyAction="http://smartorg.com/extAPI/ProjectHttpGet/UpdateCategoriesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BG_example_CallingPNwebservice1.ServiceReference1.UpdateCategoriesResponse UpdateCategories(BG_example_CallingPNwebservice1.ServiceReference1.UpdateCategoriesRequest request);
        
        // CODEGEN: Generating message contract since the operation TeamProject is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/ProjectHttpGet/TeamProjectRequest", ReplyAction="http://smartorg.com/extAPI/ProjectHttpGet/TeamProjectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BG_example_CallingPNwebservice1.ServiceReference1.TeamProjectResponse TeamProject(BG_example_CallingPNwebservice1.ServiceReference1.TeamProjectRequest request);
        
        // CODEGEN: Generating message contract since the operation DestroyAllProjects is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/ProjectHttpGet/DestroyAllProjectsRequest", ReplyAction="http://smartorg.com/extAPI/ProjectHttpGet/DestroyAllProjectsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BG_example_CallingPNwebservice1.ServiceReference1.DestroyAllProjectsResponse DestroyAllProjects(BG_example_CallingPNwebservice1.ServiceReference1.DestroyAllProjectsRequest request);
        
        // CODEGEN: Generating message contract since the operation GetProjectsExtIDs is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/ProjectHttpGet/GetProjectsExtIDsRequest", ReplyAction="http://smartorg.com/extAPI/ProjectHttpGet/GetProjectsExtIDsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BG_example_CallingPNwebservice1.ServiceReference1.GetProjectsExtIDsResponse GetProjectsExtIDs(BG_example_CallingPNwebservice1.ServiceReference1.GetProjectsExtIDsRequest request);
        
        // CODEGEN: Generating message contract since the operation CreateProject is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/ProjectHttpGet/CreateProjectRequest", ReplyAction="http://smartorg.com/extAPI/ProjectHttpGet/CreateProjectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BG_example_CallingPNwebservice1.ServiceReference1.CreateProjectResponse CreateProject(BG_example_CallingPNwebservice1.ServiceReference1.CreateProjectRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestAuthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public TestAuthRequest() {
        }
        
        public TestAuthRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestAuthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smartorg.com/extAPI/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public TestAuthResponse() {
        }
        
        public TestAuthResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCategoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string externalID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Categories;
        
        public UpdateCategoriesRequest() {
        }
        
        public UpdateCategoriesRequest(string username, string password, string externalID, string Categories) {
            this.username = username;
            this.password = password;
            this.externalID = externalID;
            this.Categories = Categories;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smartorg.com/extAPI/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BG_example_CallingPNwebservice1.ServiceReference1.ActionResult ActionResult;
        
        public UpdateCategoriesResponse() {
        }
        
        public UpdateCategoriesResponse(BG_example_CallingPNwebservice1.ServiceReference1.ActionResult ActionResult) {
            this.ActionResult = ActionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TeamProjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string externalID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string team64;
        
        public TeamProjectRequest() {
        }
        
        public TeamProjectRequest(string username, string password, string externalID, string team64) {
            this.username = username;
            this.password = password;
            this.externalID = externalID;
            this.team64 = team64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TeamProjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smartorg.com/extAPI/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BG_example_CallingPNwebservice1.ServiceReference1.ActionResult ActionResult;
        
        public TeamProjectResponse() {
        }
        
        public TeamProjectResponse(BG_example_CallingPNwebservice1.ServiceReference1.ActionResult ActionResult) {
            this.ActionResult = ActionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DestroyAllProjectsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public DestroyAllProjectsRequest() {
        }
        
        public DestroyAllProjectsRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DestroyAllProjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smartorg.com/extAPI/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public DestroyAllProjectsResponse() {
        }
        
        public DestroyAllProjectsResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectsExtIDsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public GetProjectsExtIDsRequest() {
        }
        
        public GetProjectsExtIDsRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectsExtIDsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smartorg.com/extAPI/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BG_example_CallingPNwebservice1.ServiceReference1.ProjectDefs ProjectDefs;
        
        public GetProjectsExtIDsResponse() {
        }
        
        public GetProjectsExtIDsResponse(BG_example_CallingPNwebservice1.ServiceReference1.ProjectDefs ProjectDefs) {
            this.ProjectDefs = ProjectDefs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateProjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string projectName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string projectDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string correlationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string division;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string templateName;
        
        public CreateProjectRequest() {
        }
        
        public CreateProjectRequest(string username, string password, string projectName, string projectDescription, string correlationID, string division, string templateName) {
            this.username = username;
            this.password = password;
            this.projectName = projectName;
            this.projectDescription = projectDescription;
            this.correlationID = correlationID;
            this.division = division;
            this.templateName = templateName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateProjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smartorg.com/extAPI/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BG_example_CallingPNwebservice1.ServiceReference1.ActionResult ActionResult;
        
        public CreateProjectResponse() {
        }
        
        public CreateProjectResponse(BG_example_CallingPNwebservice1.ServiceReference1.ActionResult ActionResult) {
            this.ActionResult = ActionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ProjectHttpGetChannel : BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ProjectHttpGetClient : System.ServiceModel.ClientBase<BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpGet>, BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpGet {
        
        public ProjectHttpGetClient() {
        }
        
        public ProjectHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG_example_CallingPNwebservice1.ServiceReference1.TestAuthResponse BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpGet.TestAuth(BG_example_CallingPNwebservice1.ServiceReference1.TestAuthRequest request) {
            return base.Channel.TestAuth(request);
        }
        
        public string TestAuth(string username, string password) {
            BG_example_CallingPNwebservice1.ServiceReference1.TestAuthRequest inValue = new BG_example_CallingPNwebservice1.ServiceReference1.TestAuthRequest();
            inValue.username = username;
            inValue.password = password;
            BG_example_CallingPNwebservice1.ServiceReference1.TestAuthResponse retVal = ((BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpGet)(this)).TestAuth(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG_example_CallingPNwebservice1.ServiceReference1.UpdateCategoriesResponse BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpGet.UpdateCategories(BG_example_CallingPNwebservice1.ServiceReference1.UpdateCategoriesRequest request) {
            return base.Channel.UpdateCategories(request);
        }
        
        public BG_example_CallingPNwebservice1.ServiceReference1.ActionResult UpdateCategories(string username, string password, string externalID, string Categories) {
            BG_example_CallingPNwebservice1.ServiceReference1.UpdateCategoriesRequest inValue = new BG_example_CallingPNwebservice1.ServiceReference1.UpdateCategoriesRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.externalID = externalID;
            inValue.Categories = Categories;
            BG_example_CallingPNwebservice1.ServiceReference1.UpdateCategoriesResponse retVal = ((BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpGet)(this)).UpdateCategories(inValue);
            return retVal.ActionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG_example_CallingPNwebservice1.ServiceReference1.TeamProjectResponse BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpGet.TeamProject(BG_example_CallingPNwebservice1.ServiceReference1.TeamProjectRequest request) {
            return base.Channel.TeamProject(request);
        }
        
        public BG_example_CallingPNwebservice1.ServiceReference1.ActionResult TeamProject(string username, string password, string externalID, string team64) {
            BG_example_CallingPNwebservice1.ServiceReference1.TeamProjectRequest inValue = new BG_example_CallingPNwebservice1.ServiceReference1.TeamProjectRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.externalID = externalID;
            inValue.team64 = team64;
            BG_example_CallingPNwebservice1.ServiceReference1.TeamProjectResponse retVal = ((BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpGet)(this)).TeamProject(inValue);
            return retVal.ActionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG_example_CallingPNwebservice1.ServiceReference1.DestroyAllProjectsResponse BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpGet.DestroyAllProjects(BG_example_CallingPNwebservice1.ServiceReference1.DestroyAllProjectsRequest request) {
            return base.Channel.DestroyAllProjects(request);
        }
        
        public string[] DestroyAllProjects(string username, string password) {
            BG_example_CallingPNwebservice1.ServiceReference1.DestroyAllProjectsRequest inValue = new BG_example_CallingPNwebservice1.ServiceReference1.DestroyAllProjectsRequest();
            inValue.username = username;
            inValue.password = password;
            BG_example_CallingPNwebservice1.ServiceReference1.DestroyAllProjectsResponse retVal = ((BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpGet)(this)).DestroyAllProjects(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG_example_CallingPNwebservice1.ServiceReference1.GetProjectsExtIDsResponse BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpGet.GetProjectsExtIDs(BG_example_CallingPNwebservice1.ServiceReference1.GetProjectsExtIDsRequest request) {
            return base.Channel.GetProjectsExtIDs(request);
        }
        
        public BG_example_CallingPNwebservice1.ServiceReference1.ProjectDefs GetProjectsExtIDs(string username, string password) {
            BG_example_CallingPNwebservice1.ServiceReference1.GetProjectsExtIDsRequest inValue = new BG_example_CallingPNwebservice1.ServiceReference1.GetProjectsExtIDsRequest();
            inValue.username = username;
            inValue.password = password;
            BG_example_CallingPNwebservice1.ServiceReference1.GetProjectsExtIDsResponse retVal = ((BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpGet)(this)).GetProjectsExtIDs(inValue);
            return retVal.ProjectDefs;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG_example_CallingPNwebservice1.ServiceReference1.CreateProjectResponse BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpGet.CreateProject(BG_example_CallingPNwebservice1.ServiceReference1.CreateProjectRequest request) {
            return base.Channel.CreateProject(request);
        }
        
        public BG_example_CallingPNwebservice1.ServiceReference1.ActionResult CreateProject(string username, string password, string projectName, string projectDescription, string correlationID, string division, string templateName) {
            BG_example_CallingPNwebservice1.ServiceReference1.CreateProjectRequest inValue = new BG_example_CallingPNwebservice1.ServiceReference1.CreateProjectRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.projectName = projectName;
            inValue.projectDescription = projectDescription;
            inValue.correlationID = correlationID;
            inValue.division = division;
            inValue.templateName = templateName;
            BG_example_CallingPNwebservice1.ServiceReference1.CreateProjectResponse retVal = ((BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpGet)(this)).CreateProject(inValue);
            return retVal.ActionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smartorg.com/extAPI/", ConfigurationName="ServiceReference1.ProjectHttpPost")]
    public interface ProjectHttpPost {
        
        // CODEGEN: Generating message contract since the operation TestAuth is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/ProjectHttpPost/TestAuthRequest", ReplyAction="http://smartorg.com/extAPI/ProjectHttpPost/TestAuthResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BG_example_CallingPNwebservice1.ServiceReference1.TestAuthResponse1 TestAuth(BG_example_CallingPNwebservice1.ServiceReference1.TestAuthRequest1 request);
        
        // CODEGEN: Generating message contract since the operation UpdateCategories is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/ProjectHttpPost/UpdateCategoriesRequest", ReplyAction="http://smartorg.com/extAPI/ProjectHttpPost/UpdateCategoriesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BG_example_CallingPNwebservice1.ServiceReference1.UpdateCategoriesResponse1 UpdateCategories(BG_example_CallingPNwebservice1.ServiceReference1.UpdateCategoriesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation TeamProject is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/ProjectHttpPost/TeamProjectRequest", ReplyAction="http://smartorg.com/extAPI/ProjectHttpPost/TeamProjectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BG_example_CallingPNwebservice1.ServiceReference1.TeamProjectResponse1 TeamProject(BG_example_CallingPNwebservice1.ServiceReference1.TeamProjectRequest1 request);
        
        // CODEGEN: Generating message contract since the operation DestroyAllProjects is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/ProjectHttpPost/DestroyAllProjectsRequest", ReplyAction="http://smartorg.com/extAPI/ProjectHttpPost/DestroyAllProjectsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BG_example_CallingPNwebservice1.ServiceReference1.DestroyAllProjectsResponse1 DestroyAllProjects(BG_example_CallingPNwebservice1.ServiceReference1.DestroyAllProjectsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetProjectsExtIDs is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/ProjectHttpPost/GetProjectsExtIDsRequest", ReplyAction="http://smartorg.com/extAPI/ProjectHttpPost/GetProjectsExtIDsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BG_example_CallingPNwebservice1.ServiceReference1.GetProjectsExtIDsResponse1 GetProjectsExtIDs(BG_example_CallingPNwebservice1.ServiceReference1.GetProjectsExtIDsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation CreateProject is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://smartorg.com/extAPI/ProjectHttpPost/CreateProjectRequest", ReplyAction="http://smartorg.com/extAPI/ProjectHttpPost/CreateProjectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BG_example_CallingPNwebservice1.ServiceReference1.CreateProjectResponse1 CreateProject(BG_example_CallingPNwebservice1.ServiceReference1.CreateProjectRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestAuthRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public TestAuthRequest1() {
        }
        
        public TestAuthRequest1(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestAuthResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smartorg.com/extAPI/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public TestAuthResponse1() {
        }
        
        public TestAuthResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCategoriesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string externalID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Categories;
        
        public UpdateCategoriesRequest1() {
        }
        
        public UpdateCategoriesRequest1(string username, string password, string externalID, string Categories) {
            this.username = username;
            this.password = password;
            this.externalID = externalID;
            this.Categories = Categories;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCategoriesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smartorg.com/extAPI/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BG_example_CallingPNwebservice1.ServiceReference1.ActionResult ActionResult;
        
        public UpdateCategoriesResponse1() {
        }
        
        public UpdateCategoriesResponse1(BG_example_CallingPNwebservice1.ServiceReference1.ActionResult ActionResult) {
            this.ActionResult = ActionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TeamProjectRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string externalID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string team64;
        
        public TeamProjectRequest1() {
        }
        
        public TeamProjectRequest1(string username, string password, string externalID, string team64) {
            this.username = username;
            this.password = password;
            this.externalID = externalID;
            this.team64 = team64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TeamProjectResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smartorg.com/extAPI/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BG_example_CallingPNwebservice1.ServiceReference1.ActionResult ActionResult;
        
        public TeamProjectResponse1() {
        }
        
        public TeamProjectResponse1(BG_example_CallingPNwebservice1.ServiceReference1.ActionResult ActionResult) {
            this.ActionResult = ActionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DestroyAllProjectsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public DestroyAllProjectsRequest1() {
        }
        
        public DestroyAllProjectsRequest1(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DestroyAllProjectsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smartorg.com/extAPI/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public DestroyAllProjectsResponse1() {
        }
        
        public DestroyAllProjectsResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectsExtIDsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public GetProjectsExtIDsRequest1() {
        }
        
        public GetProjectsExtIDsRequest1(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectsExtIDsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smartorg.com/extAPI/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BG_example_CallingPNwebservice1.ServiceReference1.ProjectDefs ProjectDefs;
        
        public GetProjectsExtIDsResponse1() {
        }
        
        public GetProjectsExtIDsResponse1(BG_example_CallingPNwebservice1.ServiceReference1.ProjectDefs ProjectDefs) {
            this.ProjectDefs = ProjectDefs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateProjectRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string projectName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string projectDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string correlationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string division;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string templateName;
        
        public CreateProjectRequest1() {
        }
        
        public CreateProjectRequest1(string username, string password, string projectName, string projectDescription, string correlationID, string division, string templateName) {
            this.username = username;
            this.password = password;
            this.projectName = projectName;
            this.projectDescription = projectDescription;
            this.correlationID = correlationID;
            this.division = division;
            this.templateName = templateName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateProjectResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smartorg.com/extAPI/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BG_example_CallingPNwebservice1.ServiceReference1.ActionResult ActionResult;
        
        public CreateProjectResponse1() {
        }
        
        public CreateProjectResponse1(BG_example_CallingPNwebservice1.ServiceReference1.ActionResult ActionResult) {
            this.ActionResult = ActionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ProjectHttpPostChannel : BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ProjectHttpPostClient : System.ServiceModel.ClientBase<BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpPost>, BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpPost {
        
        public ProjectHttpPostClient() {
        }
        
        public ProjectHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG_example_CallingPNwebservice1.ServiceReference1.TestAuthResponse1 BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpPost.TestAuth(BG_example_CallingPNwebservice1.ServiceReference1.TestAuthRequest1 request) {
            return base.Channel.TestAuth(request);
        }
        
        public string TestAuth(string username, string password) {
            BG_example_CallingPNwebservice1.ServiceReference1.TestAuthRequest1 inValue = new BG_example_CallingPNwebservice1.ServiceReference1.TestAuthRequest1();
            inValue.username = username;
            inValue.password = password;
            BG_example_CallingPNwebservice1.ServiceReference1.TestAuthResponse1 retVal = ((BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpPost)(this)).TestAuth(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG_example_CallingPNwebservice1.ServiceReference1.UpdateCategoriesResponse1 BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpPost.UpdateCategories(BG_example_CallingPNwebservice1.ServiceReference1.UpdateCategoriesRequest1 request) {
            return base.Channel.UpdateCategories(request);
        }
        
        public BG_example_CallingPNwebservice1.ServiceReference1.ActionResult UpdateCategories(string username, string password, string externalID, string Categories) {
            BG_example_CallingPNwebservice1.ServiceReference1.UpdateCategoriesRequest1 inValue = new BG_example_CallingPNwebservice1.ServiceReference1.UpdateCategoriesRequest1();
            inValue.username = username;
            inValue.password = password;
            inValue.externalID = externalID;
            inValue.Categories = Categories;
            BG_example_CallingPNwebservice1.ServiceReference1.UpdateCategoriesResponse1 retVal = ((BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpPost)(this)).UpdateCategories(inValue);
            return retVal.ActionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG_example_CallingPNwebservice1.ServiceReference1.TeamProjectResponse1 BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpPost.TeamProject(BG_example_CallingPNwebservice1.ServiceReference1.TeamProjectRequest1 request) {
            return base.Channel.TeamProject(request);
        }
        
        public BG_example_CallingPNwebservice1.ServiceReference1.ActionResult TeamProject(string username, string password, string externalID, string team64) {
            BG_example_CallingPNwebservice1.ServiceReference1.TeamProjectRequest1 inValue = new BG_example_CallingPNwebservice1.ServiceReference1.TeamProjectRequest1();
            inValue.username = username;
            inValue.password = password;
            inValue.externalID = externalID;
            inValue.team64 = team64;
            BG_example_CallingPNwebservice1.ServiceReference1.TeamProjectResponse1 retVal = ((BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpPost)(this)).TeamProject(inValue);
            return retVal.ActionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG_example_CallingPNwebservice1.ServiceReference1.DestroyAllProjectsResponse1 BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpPost.DestroyAllProjects(BG_example_CallingPNwebservice1.ServiceReference1.DestroyAllProjectsRequest1 request) {
            return base.Channel.DestroyAllProjects(request);
        }
        
        public string[] DestroyAllProjects(string username, string password) {
            BG_example_CallingPNwebservice1.ServiceReference1.DestroyAllProjectsRequest1 inValue = new BG_example_CallingPNwebservice1.ServiceReference1.DestroyAllProjectsRequest1();
            inValue.username = username;
            inValue.password = password;
            BG_example_CallingPNwebservice1.ServiceReference1.DestroyAllProjectsResponse1 retVal = ((BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpPost)(this)).DestroyAllProjects(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG_example_CallingPNwebservice1.ServiceReference1.GetProjectsExtIDsResponse1 BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpPost.GetProjectsExtIDs(BG_example_CallingPNwebservice1.ServiceReference1.GetProjectsExtIDsRequest1 request) {
            return base.Channel.GetProjectsExtIDs(request);
        }
        
        public BG_example_CallingPNwebservice1.ServiceReference1.ProjectDefs GetProjectsExtIDs(string username, string password) {
            BG_example_CallingPNwebservice1.ServiceReference1.GetProjectsExtIDsRequest1 inValue = new BG_example_CallingPNwebservice1.ServiceReference1.GetProjectsExtIDsRequest1();
            inValue.username = username;
            inValue.password = password;
            BG_example_CallingPNwebservice1.ServiceReference1.GetProjectsExtIDsResponse1 retVal = ((BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpPost)(this)).GetProjectsExtIDs(inValue);
            return retVal.ProjectDefs;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BG_example_CallingPNwebservice1.ServiceReference1.CreateProjectResponse1 BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpPost.CreateProject(BG_example_CallingPNwebservice1.ServiceReference1.CreateProjectRequest1 request) {
            return base.Channel.CreateProject(request);
        }
        
        public BG_example_CallingPNwebservice1.ServiceReference1.ActionResult CreateProject(string username, string password, string projectName, string projectDescription, string correlationID, string division, string templateName) {
            BG_example_CallingPNwebservice1.ServiceReference1.CreateProjectRequest1 inValue = new BG_example_CallingPNwebservice1.ServiceReference1.CreateProjectRequest1();
            inValue.username = username;
            inValue.password = password;
            inValue.projectName = projectName;
            inValue.projectDescription = projectDescription;
            inValue.correlationID = correlationID;
            inValue.division = division;
            inValue.templateName = templateName;
            BG_example_CallingPNwebservice1.ServiceReference1.CreateProjectResponse1 retVal = ((BG_example_CallingPNwebservice1.ServiceReference1.ProjectHttpPost)(this)).CreateProject(inValue);
            return retVal.ActionResult;
        }
    }
}
